### ISSUE TITLE
I want to use your dataset to make lmdb in caffe

### ISSUE THREAD

**Issue by gittigxuy** [layumi/DukeMTMC-reID_evaluation#2]
As  you know,when we make lmdb file,we should use txt file ,but in your dataset ,I could not find the  txt file.So could you please provide me the txt file in your dataSet? I find that there are three files,boundingbox_train,bounding_test and query.So could you please provide these txt files to me ?

**Comment by zhunzhong07** [comment]
`clear all;

train_id = importdata('train_label.mat');

sum_train = 1;

train_file = [];

file_path = 'bounding_box_train/';

se_dir = dir([file_path '*.jpg']);
for n = 1:length(se_dir)
    n
    img_name = se_dir(n).name;
    %label = str2num(img_name(1:4));
    if n==1
        label = 0;
    else
        if train_id(n - 1) ~= train_id(n)
            label = label + 1;
        end
    end
    imgpath = [file_path img_name];
    train_file{sum_train} = [imgpath ' ' num2str(label)];
    sum_train = sum_train + 1;
end


fp = fopen(['train.txt'],'wt');
for i =1 : size(train_file, 2)
    fprintf(fp, '%s\n', train_file{1,i});
end
fclose(fp);

`

**Comment by zhunzhong07** [comment]
'''
clear all;

train_id = importdata('train_label.mat');

sum_train = 1;

train_file = [];

file_path = 'bounding_box_train/';

se_dir = dir([file_path '*.jpg']);
for n = 1:length(se_dir)
    n
    img_name = se_dir(n).name;
    %label = str2num(img_name(1:4));
    if n==1
        label = 0;
    else
        if train_id(n - 1) ~= train_id(n)
            label = label + 1;
        end
    end
    imgpath = [file_path img_name];
    train_file{sum_train} = [imgpath ' ' num2str(label)];
    sum_train = sum_train + 1;
end


fp = fopen(['train.txt'],'wt');
for i =1 : size(train_file, 2)
    fprintf(fp, '%s\n', train_file{1,i});
end
fclose(fp);


'''

**Comment by zhunzhong07** [comment]
```gen_trainlist.m
clear all;

train_id = importdata('train_label.mat');

sum_train = 1;

train_file = [];

file_path = 'bounding_box_train/';

se_dir = dir([file_path '*.jpg']);
for n = 1:length(se_dir)
    n
    img_name = se_dir(n).name;
    %label = str2num(img_name(1:4));
    if n==1
        label = 0;
    else
        if train_id(n - 1) ~= train_id(n)
            label = label + 1;
        end
    end
    imgpath = [file_path img_name];
    train_file{sum_train} = [imgpath ' ' num2str(label)];
    sum_train = sum_train + 1;
end


fp = fopen(['train.txt'],'wt');
for i =1 : size(train_file, 2)
    fprintf(fp, '%s\n', train_file{1,i});
end
fclose(fp);
    ```

**Comment by layumi** [comment]
Hi @gittigxuy 
I write a code to generate train_list for caffe. You can check it
https://github.com/layumi/DukeMTMC-reID_evaluation/blob/master/generate_train_list_caffe.m 

Or directly use my generated train list.
https://github.com/layumi/DukeMTMC-reID_evaluation/blob/master/train_list.txt
