### ISSUE TITLE
Do you have the Source code of Bilinear Coding Mention it in your /State-of-the-art/README.md

### ISSUE THREAD

**Issue by Mr-zhu0912** [layumi/DukeMTMC-reID_evaluation#3]
Hi,
Recently I prepared to repetition "Weighted Bilinear Coding over Salient Body Parts for Person Re-identification",and to improve my model.But i don't find the source code,search in github,just find you repository refer to it.so, If you have it ,can sent it to my email,and my email is 2941746806@qq.com.
end,thank you a lot!
![snipaste_20180510_184103](https://user-images.githubusercontent.com/35393647/39866401-279f9f3c-5483-11e8-90a2-052e98c95e4a.png)

**Comment by layumi** [comment]
****
