### ISSUE TITLE
Do you have the Source code of DPFL Coding Mention it in your /State-of-the-art/README.md

### ISSUE THREAD

**Issue by LMAhu** [layumi/DukeMTMC-reID_evaluation#5]
Hello,
Firstly,thank you very much for these,Recently I prepared to repetition "Person Re-Identification by Deep Learning Multi-Scale Representations",.But i don't find the source code,search in github,just find you repository refer to it.so, If you have it ,can sent it to my email,and my email is 1691416208@qq.com.
,thank you a lot!
![image](https://user-images.githubusercontent.com/40314876/41497341-45cc12a4-7186-11e8-8d49-81e35d14523c.png)

**Comment by layumi** [comment]
Hi @LMAhu 
You may refer to https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/model.py#L98
I have written a simple version.

**Comment by LMAhu** [comment]
Thank you for your reply!
