### ISSUE TITLE
Do you have the code for the paper of Dual Attention Matching Network for Context-Aware Feature Sequence based Person Re-Identification?

### ISSUE THREAD

**Issue by Adorablepet** [layumi/DukeMTMC-reID_evaluation#6]
Hello，
First of all, I am very grateful for the information compiled. I didn't find the code implementation of this paper on github. I don't know if you have there. I want to know the attention mechanism. If so, can you provide some learning? Thanks again.

**Comment by layumi** [comment]
Hi  @Adorablepet ,
You may find the code at [Here](https://github.com/layumi/Person-reID_GAN).

**Comment by Adorablepet** [comment]
@layumi I didn't find out about DuATM‘s code, you can say in details.Thanks.

**Comment by layumi** [comment]
You may email the author of that paper.
